### ISSUE TITLE
Oneechan Crashing Tabs Memory Related

### ISSUE THREAD

**Issue by CharAznableLoNZ** [KevinParnell/OneeChan#15] opened 2019-05-25 11:20 UTC
Crash below.  Could indicate a memory leak.

Thread 0 (id: 0x00007e62) CRASHED [SIGTRAP @ 0x00000000 ] MAGIC SIGNATURE THREAD
Stack Quality100%Show frame trust levels
0x0000557d480818bc	(chrome -heap_page.cc:677 )	blink::NormalPageArena::AllocatePage()
0x0000557d48082471	(chrome -heap_page.cc:929 )	blink::NormalPageArena::OutOfLineAllocate(unsigned long, unsigned long)
0x0000557d4b6bd4ff	(chrome -heap_page.h:1056 )	WTF::KeyValuePair<WTF::AtomicString, blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > >* blink::HeapAllocator::AllocateHashTableBacking<WTF::KeyValuePair<WTF::AtomicString, blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > >, WTF::HashTable<WTF::AtomicString, WTF::KeyValuePair<WTF::AtomicString, blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > >, WTF::KeyValuePairKeyExtractor, WTF::AtomicStringHash, WTF::HashMapValueTraits<WTF::HashTraitsWTF::AtomicString, WTF::HashTraits<blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > > >, WTF::HashTraitsWTF::AtomicString, blink::HeapAllocator> >(unsigned long)
0x0000557d4b6bd011	(chrome -heap_allocator.h:126 )	WTF::HashTable<WTF::AtomicString, WTF::KeyValuePair<WTF::AtomicString, blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > >, WTF::KeyValuePairKeyExtractor, WTF::AtomicStringHash, WTF::HashMapValueTraits<WTF::HashTraitsWTF::AtomicString, WTF::HashTraits<blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > > >, WTF::HashTraitsWTF::AtomicString, blink::HeapAllocator>::Expand(WTF::KeyValuePair<WTF::AtomicString, blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > >)
0x0000557d4b6bcf33	(chrome -hash_table.h:1357 ) WTF::HashTableAddResult<WTF::HashTable<WTF::AtomicString, WTF::KeyValuePair<WTF::AtomicString, blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > >, WTF::KeyValuePairKeyExtractor, WTF::AtomicStringHash, WTF::HashMapValueTraits<WTF::HashTraitsWTF::AtomicString, WTF::HashTraits<blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > > >, WTF::HashTraitsWTF::AtomicString, blink::HeapAllocator>, WTF::KeyValuePair<WTF::AtomicString, blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > > > WTF::HashTable<WTF::AtomicString, WTF::KeyValuePair<WTF::AtomicString, blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > >, WTF::KeyValuePairKeyExtractor, WTF::AtomicStringHash, WTF::HashMapValueTraits<WTF::HashTraitsWTF::AtomicString, WTF::HashTraits<blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > > >, WTF::HashTraitsWTF::AtomicString, blink::HeapAllocator>::insert<WTF::HashMapTranslator<WTF::HashMapValueTraits<WTF::HashTraitsWTF::AtomicString, WTF::HashTraits<blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > > >, WTF::AtomicStringHash, blink::HeapAllocator>, WTF::AtomicString const&, std::nullptr_t>(WTF::AtomicString const&, std::nullptr_t&&)
0x0000557d4b6b9705	(chrome -hash_map.h:542 )	blink::RuleSet::AddToRuleSet(WTF::AtomicString const&, blink::HeapHashMap<WTF::AtomicString, blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > >, WTF::AtomicStringHash, WTF::HashTraitsWTF::AtomicString, WTF::HashTraits<blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > > >&, blink::RuleData const)
0x0000557d4b6b9cf6	(chrome -rule_set.cc )	blink::RuleSet::AddRule(blink::StyleRule*, unsigned int, blink::AddRuleFlags)
0x0000557d4b6ba70a	(chrome -rule_set.cc:311 ) blink::RuleSet::AddChildRules(blink::HeapVector<blink::Memberblink::StyleRuleBase, 0u> const&, blink::MediaQueryEvaluator const&, blink::AddRuleFlags)
0x0000557d4b6ba9d4	(chrome -rule_set.cc:355 ) blink::RuleSet::AddRulesFromSheet(blink::StyleSheetContents*, blink::MediaQueryEvaluator const&, blink::AddRuleFlags)
0x0000557d4b6e9afc	(chrome -style_sheet_contents.cc:605 ) blink::StyleSheetContents::EnsureRuleSet(blink::MediaQueryEvaluator const&, blink::AddRuleFlags)
0x0000557d4b6c88ff	(chrome -style_engine.cc:576 ) blink::StyleEngine::RuleSetForSheet(blink::CSSStyleSheet&)
0x0000557d4b6d9704	(chrome -document_style_sheet_collection.cc:89 ) blink::DocumentStyleSheetCollection::CollectStyleSheets(blink::StyleEngine&, blink::DocumentStyleSheetCollector&)
0x0000557d4b6d993b	(chrome -document_style_sheet_collection.cc:129 ) blink::DocumentStyleSheetCollection::UpdateActiveStyleSheets(blink::StyleEngine&)
0x0000557d4b6c89c8	(chrome -style_engine.cc:458 )	blink::StyleEngine::UpdateActiveStyleSheets()
0x0000557d4b6c7325	(chrome -style_engine.cc:497 )	blink::StyleEngine::UpdateActiveStyle()
0x0000557d4b7096e3	(chrome -document.cc:2284 )	blink::Document::UpdateActiveStyle()
0x0000557d4b707560	(chrome -document.cc:2237 )	blink::Document::UpdateStyleAndLayoutTree()
0x0000557d4b947297	(chrome -local_frame_view.cc:659 )	blink::LocalFrameView::UpdateLayout()
0x0000557d4b947c49	(chrome -local_frame_view.cc:916 )	blink::LocalFrameView::UpdateLayout()
0x0000557d4b94e0cc	(chrome -local_frame_view.cc:2867 ) blink::LocalFrameView::UpdateStyleAndLayoutIfNeededRecursive()
0x0000557d4b94cb61	(chrome -local_frame_view.cc:2298 ) blink::LocalFrameView::UpdateLifecyclePhases(blink::DocumentLifecycle::LifecycleState, blink::DocumentLifecycle::LifecycleUpdateReason)
0x0000557d4be570bf	(chrome -page_animator.cc:108 ) blink::PageAnimator::UpdateAllLifecyclePhases(blink::LocalFrame&, blink::DocumentLifecycle::LifecycleUpdateReason)
0x0000557d4b8a1159	(chrome -web_view_impl.cc:1594 ) blink::WebViewImpl::UpdateLifecycle(blink::WebWidget::LifecycleUpdate, blink::WebWidget::LifecycleUpdateReason)
0x0000557d4b8a00e1	(chrome -web_widget.h:146 )	blink::WebViewImpl::ResizeViewWhileAnchored(float, float, bool)
0x0000557d4b8a0327	(chrome -web_view_impl.cc:1444 ) blink::WebViewImpl::ResizeWithBrowserControls(blink::WebSize const&, float, float, bool)
0x0000557d4cb195e2	(chrome -render_view_impl.cc:1195 )	non-virtual thunk to content::RenderViewImpl::ResizeWebWidgetForWidget(gfx::Size const&, float, float, bool)
0x0000557d4cb29991	(chrome -render_widget.cc:1563 ) content::RenderWidget::SynchronizeVisualProperties(content::VisualProperties const&)
0x0000557d4cb24d28	(chrome -render_widget.cc:889 ) content::RenderWidget::OnSynchronizeVisualProperties(content::VisualProperties const&)
0x0000557d4cb20bc7	(chrome -tuple.h:52 )	content::RenderWidget::OnMessageReceived(IPC::Message const&)
0x0000557d48e4c209	(chrome -ipc_channel_proxy.cc:324 ) IPC::ChannelProxy::Context::OnDispatchMessage(IPC::Message const&)
0x0000557d488d99da	(chrome -callback.h:97 )	base::TaskAnnotator::RunTask(char const*, base::PendingTask*)
0x0000557d488da595	(chrome -thread_controller_with_message_pump_impl.cc:363 ) base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*, bool*)
0x0000557d488da374	(chrome -thread_controller_with_message_pump_impl.cc:214 ) base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoSomeWork()
0x0000557d48899525	(chrome -message_pump_default.cc:39 ) base::MessagePumpDefault::Run(base::MessagePump::Delegate*)
0x0000557d488dadc4	(chrome -thread_controller_with_message_pump_impl.cc:448 ) base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta)
0x0000557d488b76ae	(chrome -run_loop.cc:161 )	base::RunLoop::RunWithTimeout(base::TimeDelta)
0x0000557d4cb5d746	(chrome -renderer_main.cc:223 ) content::RendererMain(content::MainFunctionParams const&)
0x0000557d4848d222	(chrome -content_main_runner_impl.cc:513 ) content::ContentMainRunnerImpl::Run(bool)
0x0000557d484c36ba	(chrome -main.cc:415 )	service_manager::Main(service_manager::MainParams const&)
0x0000557d4848b1b0	(chrome -content_main.cc:19 )	content::ContentMain(content::ContentMainParams const&)
0x0000557d464645b2	(chrome -chrome_main.cc:103 )	ChromeMain
0x00007f2b54035b96	(libc-2.27.so -libc-start.c:310 )	__libc_start_main
0x0000557d461a7029	(chrome + 0x0199f029 )	_start
0x00007ffe7a665b47

**Comment by CharAznableLoNZ** [comment] 2019-05-26 02:59
This causes all 4channel tabs to crash a few times a day.  Highly annoying to deal with.

**Comment by CharAznableLoNZ** [comment] 2019-05-26 05:58
Third time it's crashed tonight.

**Comment by CharAznableLoNZ** [comment] 2019-05-26 06:54
Forth time tonight.

**Comment by CharAznableLoNZ** [comment] 2019-05-26 08:00
Fifth time.

**Comment by CharAznableLoNZ** [comment] 2019-05-26 09:16
Sixth time.

**Comment by CharAznableLoNZ** [comment] 2019-05-26 21:48
Seventh time.

**Comment by CharAznableLoNZ** [comment] 2019-05-28 08:40
And again.

**Comment by CharAznableLoNZ** [comment] 2019-05-30 21:57
Ninth time.  Anyone there?

**Comment by KevinParnell** [comment] 2019-05-31 19:05
If you keep spamming this I will lock it. I haven’t been on 4channel in a bit so I’ll check it out tonight when I get off work. I’m not aware of anyone in my discord having this issue.

**Comment by KevinParnell** [comment] 2019-05-31 19:12
Talked with some people in my discord, either get more ram or it’s just chrome. Not to mention that your error report makes no mention of oneechan, just basic functions of chrome fucking up. I’m pretty positive the issue isn’t oneechan, so I’m closing this issue. I’ll still test it tonight and if it does crash, I’ll reopen the issue and look further into it.

**Comment by KevinParnell** [comment] 2019-05-31 19:15
Also there’s a much higher chance this is a 4chanx issue rather than an oneechan issue. Please refer to the readme next time before you post an issue. https://github.com/ccd0/4chan-x/issues/2304

**Comment by CharAznableLoNZ** [comment] 2019-06-03 05:19
We've already been through this with the folks running 4chanx.  From what they can tell, the crash happens due to style sheets eating memory.

> According to the crash log, the browser is crashing because it's failing to allocate memory while updating stylesheets.

So either your computer is just really low on memory, or something in the page is causing a major leak (if this is the case it's probably oneechan). It also explains why tabs might go unresponsive, that's normal when memory is being paged out. You'll have to look at your computer's and chrome's task managers to see what's actually causing it.

At the time of a crash, the machine had 12GB free of RAM.

**Comment by KevinParnell** [comment] 2019-06-06 19:27
Does this happen in a different browser? I have other folks using Chrome and other browsers and none of them are running into this issue.

**Comment by CharAznableLoNZ** [comment] 2019-06-08 00:35
I've tried with Firefox however that has other issues with the amount of tabs before getting to the point of this kind of crash.  The odd part of the behavior is only the 4channel tabs crash, the 4chan tabs are left alone even if the crash occurs.  It takes quite a few tabs open though to get it to a point where a crash occurs.  Below is the config exported.


[https://files.catbox.moe/ose6r2.json](url)

**Comment by KevinParnell** [comment] 2020-01-21 18:04
Is it still happening?

**Closed by KevinParnell** 2020-01-21 18:04 UTC

**Comment by CharAznableLoNZ** [comment] 2020-02-12 11:28
I started using The Great Suspender to free up RAM.  Issue went away.
